ritish_a = int(input("Enter any integer: "))
ritish_b = float(input("Enter any float no.: "))
ritish_c = complex(input("Enter any complex no.: "))
ritish_d = input("Enter string: ")
ritish_e = [1,45,56,45.6,"Ritish Bhatoye"]
ritish_f = ("hello",5,5.6,"a")
ritish_g = {"ID_no":207025, "Age":19, "Marks":88.67}
print("\n\nNumeric Data types: ")
print(ritish_a)
print(type(ritish_a))
print(ritish_b)
print(type(ritish_b))
print(ritish_c)
print(type(ritish_c))
print("\n\nString data type: ")
print(ritish_d)
print(type(ritish_d))
print("\n\nData structures: ")
print(ritish_e)
print(type(ritish_e))
print(ritish_f)
print(type(ritish_f))
print(ritish_g)
print(type(ritish_g))
